// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiBooks.Repositories;

namespace WebApiBooks.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20190821170214_EFCoreCodeFirstSample.Models.RepositoryContext")]
    partial class EFCoreCodeFirstSampleModelsRepositoryContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiBooks.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("NameBook");

                    b.Property<int>("Page");

                    b.HasKey("Id");

                    b.ToTable("book");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd7d39cc-115a-4abe-a588-a76318fcc30c"),
                            Author = "Andrew Troelsen",
                            NameBook = "C# 7 .Net Core",
                            Page = 1328
                        },
                        new
                        {
                            Id = new Guid("5a8fc52c-27e2-4459-a9a0-9dfc844ad4f5"),
                            Author = "Allen G.Taylor",
                            NameBook = "SQL",
                            Page = 402
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
