// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiBooks.Repositories;

namespace WebApiBooks.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20190820162644_EFCoreCodeFirstSample.Models.BookContextSeed")]
    partial class EFCoreCodeFirstSampleModelsBookContextSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiBooks.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<int>("Page");

                    b.Property<string>("nameBook");

                    b.HasKey("BookId");

                    b.ToTable("book");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Andrew Troelsen",
                            Page = 1328,
                            nameBook = "C# 7 .Net Core"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Allen G.Taylor",
                            Page = 402,
                            nameBook = "SQL"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
